services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: music-backend
    env_file:
      - ./backend/.env
    environment:
       - CHATBOT_URL=http://chatbot:8000
       - MONGO_URI=mongodb://mongo:27017/musicdb  
    ports:
      - "4000:4000"
    depends_on:
      - chatbot
      - mongo
    restart: unless-stopped

  chatbot:
    build:
      context: ./chatbot
      dockerfile: dockerfile  
    container_name: music-chatbot
    env_file:
      - ./chatbot/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend_2
      dockerfile: Dockerfile
    container_name: music-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
      - VITE_CHATBOT_URL=http://localhost:8000
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: music-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped

volumes:
  mongo-data:
